# Data Aggregation using Pandas

In [3]:
# import the pandas library
import pandas as pd

In [4]:
# read in the data
safi = pd.read_csv('data/SAFI_clean.csv')

In [5]:
# use describe() to get summary statistics of the data
safi.describe()

           key_ID  no_membrs   years_liv       rooms   liv_count    no_meals
count  131.000000  131.00000  131.000000  131.000000  131.000000  131.000000
mean    85.473282    7.19084   23.053435    1.740458    2.366412    2.603053
std     63.151628    3.17227   16.913041    1.092547    1.082775    0.491143
min      1.000000    2.00000    1.000000    1.000000    1.000000    2.000000
25%     32.500000    5.00000   12.000000    1.000000    1.000000    2.000000
50%     66.000000    7.00000   20.000000    1.000000    2.000000    3.000000
75%    138.000000    9.00000   27.500000    2.000000    3.000000    3.000000
max    202.000000   19.00000   96.000000    8.000000    5.000000    3.000000

In [6]:
safi.max()

key_ID                                                        202
village                                                     Ruaca
interview_date                               2017-06-04T00:00:00Z
no_membrs                                                      19
years_liv                                                      96
respondent_wall_type                                    sunbricks
rooms                                                           8
liv_count                                                       5
no_meals                                                        3
months_lack_food                                             none
instanceID              uuid:ffc83162-ff24-4a87-8709-eff17abc0b3b
dtype: object

In [7]:
safi['rooms'].mean()

1.7404580152671756

### What to do with categorial/text data?

In [8]:
# get unique entries of a variable
safi['village'].unique()

array(['God', 'Chirodzo', 'Ruaca'], dtype=object)

In [9]:
safi['village'].count()

131

# %load code/counts
1. Get the unique entries for the `affect_conflicts` variable
2. Get the count value for `affect_conflicts` and compare it with the count for `respondent_wall_type`.
3. Why do you think they are different?

### Solutions to exercise

In [15]:
# 1.
safi['affect_conflicts'].unique()

array([nan, 'once', 'never', 'more_once', 'frequently'], dtype=object)

In [16]:
# 2.
safi['affect_conflicts'].count()

92

3. the count for 'affect_conflicts' is 92 and the count for 'villages' or 'respondent_wall_type' was 131. The reason for the difference is: there are missing values (indicated by NaN) in 'affect_conflicts' which are not counted (see below)

In [17]:
safi['affect_conflicts']

0             NaN
1            once
2             NaN
3             NaN
4             NaN
5             NaN
6           never
7           never
8           never
9           never
10            NaN
11          never
12          never
13            NaN
14           once
15            NaN
16            NaN
17            NaN
18            NaN
19            NaN
20          never
21            NaN
22            NaN
23          never
24          never
25          never
26            NaN
27      more_once
28     frequently
29            NaN
          ...
101    frequently
102         never
103           NaN
104         never
105         never
106           NaN
107     more_once
108         never
109           NaN
110         never
111           NaN
112           NaN
113    frequently
114    frequently
115         never
116         never
117    frequently
118         never
119         never
120         never
121         never
122         never
123         never
124         never
125          once
126     more_once
127     more_once
128     more_once
129     more_once
130           NaN
Name: affect_conflicts, Length: 131, dtype: object

In [18]:
# test DataFram for missing values --> False = cell is not a missing value, True = cell is a missing value
safi.isna()

,key_ID,village,interview_date,no_membrs,years_liv,respondent_wall_type,rooms,memb_assoc,affect_conflicts,liv_count,items_owned,no_meals,months_lack_food,instanceID
0,False,False,False,False,False,False,False,True,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,True,True,False,False,False,False,False
3,False,False,False,False,False,False,False,True,True,False,False,False,False,False
4,False,False,False,False,False,False,False,True,True,False,False,False,False,False
5,False,False,False,False,False,False,False,True,True,False,True,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,True,True,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,True,True,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,True,True,False,False,False,False,False
16,False,False,False,False,False,False,False,True,True,False,False,False,False,False
17,False,False,False,False,False,False,False,True,True,False,False,False,False,False
18,False,False,False,False,False,False,False,True,True,False,False,False,False,False
19,False,False,False,False,False,False,False,True,True,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,True,False,False,False
21,False,False,False,False,False,False,False,True,True,False,False,False,False,False
22,False,False,False,False,False,False,False,True,True,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,True,True,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,True,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,True,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,False,False,False,False,False,False,False,False,False,False,False,False,False,False
102,False,False,False,False,False,False,False,False,False,False,False,False,False,False
103,False,False,False,False,False,False,False,True,True,False,False,False,False,False
104,False,False,False,False,False,False,False,False,False,False,False,False,False,False
105,False,False,False,False,False,False,False,False,False,False,False,False,False,False
106,False,False,False,False,False,False,False,True,True,False,False,False,False,False
107,False,False,False,False,False,False,False,False,False,False,False,False,False,False
108,False,False,False,False,False,False,False,False,False,False,False,False,False,False
109,False,False,False,False,False,False,False,True,True,False,False,False,False,False
110,False,False,False,False,False,False,False,False,False,False,False,False,False,False
111,False,False,False,False,False,False,False,True,True,False,False,False,False,False
112,False,False,False,False,False,False,False,True,True,False,False,False,False,False
113,False,False,False,False,False,False,False,False,False,False,False,False,False,False
114,False,False,False,False,False,False,False,False,False,False,False,False,False,False
115,False,False,False,False,False,False,False,False,False,False,False,False,False,False
116,False,False,False,False,False,False,False,False,False,False,False,False,False,False
117,False,False,False,False,False,False,False,False,False,False,False,False,False,False
118,False,False,False,False,False,False,False,False,False,False,False,False,False,False
119,False,False,False,False,False,False,False,False,False,False,False,False,False,False
120,False,False,False,False,False,False,False,False,False,False,False,False,False,False
121,False,False,False,False,False,False,False,False,False,False,False,False,False,False
122,False,False,False,False,False,False,False,False,False,False,False,False,False,False
123,False,False,False,False,False,False,False,False,False,False,False,False,False,False
124,False,False,False,False,False,False,False,False,False,False,False,False,False,False
125,False,False,False,False,False,False,False,False,False,False,False,False,False,False
126,False,False,False,False,False,False,False,False,False,False,False,False,False,False
127,False,False,False,False,False,False,False,False,False,False,False,False,False,False
128,False,False,False,False,False,False,False,False,False,False,False,False,False,False
129,False,False,False,False,False,False,False,False,False,False,False,False,False,False
130,False,False,False,False,False,False,False,True,True,False,False,False,False,False

In [19]:
# get the count of missing values for each column in safi DataFrame by summing over each column 
# --> False is represented by 0 and True by 1 in python
safi.isna().sum()

key_ID                   0
village                  0
interview_date           0
no_membrs                0
years_liv                0
respondent_wall_type     0
rooms                    0
memb_assoc              39
affect_conflicts        39
liv_count                0
items_owned             10
no_meals                 0
months_lack_food         0
instanceID               0
dtype: int64

In [20]:
# remove all rows where any of the columns has a missing value
safi.dropna()

,key_ID,village,interview_date,no_membrs,years_liv,respondent_wall_type,rooms,memb_assoc,affect_conflicts,liv_count,items_owned,no_meals,months_lack_food,instanceID
1,1,God,2016-11-17T00:00:00Z,7,9,muddaub,1,yes,once,3,cow_cart;bicycle;radio;cow_plough;solar_panel;...,2,Jan;Sept;Oct;Nov;Dec,uuid:099de9c9-3e5e-427b-8452-26250e840d6e
6,7,God,2016-11-17T00:00:00Z,6,38,muddaub,1,no,never,1,motorcyle;cow_plough,3,Nov,uuid:ae20a58d-56f4-43d7-bafa-e7963d850844
7,8,Chirodzo,2016-11-16T00:00:00Z,12,70,burntbricks,3,yes,never,2,motorcyle;bicycle;television;radio;cow_plough;...,2,Jan,uuid:d6cee930-7be1-4fd9-88c0-82a08f90fb5a
8,9,Chirodzo,2016-11-16T00:00:00Z,8,6,burntbricks,1,no,never,3,television;solar_panel;solar_torch,3,Jan;Dec,uuid:846103d2-b1db-4055-b502-9cd510bb7b37
9,10,Chirodzo,2016-12-16T00:00:00Z,12,23,burntbricks,5,no,never,2,cow_cart;motorcyle;bicycle;television;radio;co...,3,Jan;Oct;Nov;Dec,uuid:8f4e49bc-da81-4356-ae34-e0d794a23721
11,12,God,2016-11-21T00:00:00Z,7,20,burntbricks,3,yes,never,2,cow_cart;bicycle;radio;cow_plough;table,3,Sept;Oct,uuid:e6ee6269-b467-4e37-91fc-5e9eaf934557
12,13,God,2016-11-21T00:00:00Z,6,8,burntbricks,1,no,never,3,bicycle;radio;cow_plough;mobile_phone,2,Sept;Oct;Nov,uuid:6c00c145-ee3b-409c-8c02-2c8d743b6918
14,15,God,2016-11-21T00:00:00Z,5,30,sunbricks,2,yes,once,3,bicycle;radio;cow_plough;solar_panel;table,2,Jan;Feb;Mar;Apr;May;June;July;Aug;Sept;Oct;Nov,uuid:a837e545-ff86-4a1c-a1a5-6186804b985f
23,24,Ruaca,2016-11-21T00:00:00Z,6,4,burntbricks,2,no,never,3,radio;table;sofa_set;mobile_phone,2,Nov;Dec,uuid:661457d3-7e61-45e8-a238-7415e7548f82
24,25,Ruaca,2016-11-21T00:00:00Z,11,6,burntbricks,3,no,never,2,cow_cart;motorcyle;television;radio;cow_plough...,2,Jan;Feb;Oct,uuid:45ed84c4-114e-4df0-9f5d-c800806c2bee
25,26,Ruaca,2016-11-21T00:00:00Z,3,20,burntbricks,2,no,never,2,radio;cow_plough;table;mobile_phone,2,none,uuid:1c54ee24-22c4-4ee9-b1ad-42d483c08e2e
28,29,Ruaca,2016-11-21T00:00:00Z,7,10,burntbricks,2,yes,frequently,1,motorcyle;bicycle;radio;table;mobile_phone,3,Jan;Feb,uuid:adcd7463-8943-4c67-b25f-f72311409476
31,32,Ruaca,2016-11-21T00:00:00Z,19,69,muddaub,2,yes,more_once,5,cow_cart;motorcyle;radio;cow_plough;solar_pane...,2,none,uuid:25597af3-cd79-449c-a48a-fb9aea6c48bf
32,33,Ruaca,2016-11-21T00:00:00Z,8,34,muddaub,1,no,more_once,2,cow_cart;lorry;motorcyle;sterio;cow_plough;sol...,2,none,uuid:0fbd2df1-2640-4550-9fbd-7317feaa4758
33,34,Chirodzo,2016-11-17T00:00:00Z,8,18,burntbricks,3,yes,more_once,3,television;radio;cow_plough;solar_panel;solar_...,2,Jan;Dec,uuid:14c78c45-a7cc-4b2a-b765-17c82b43feb4
34,35,Chirodzo,2016-11-17T00:00:00Z,5,45,muddaub,1,yes,more_once,2,bicycle;cow_plough,3,Jan;Sept;Oct;Nov;Dec,uuid:ff7496e7-984a-47d3-a8a1-13618b5683ce
35,36,Chirodzo,2016-11-17T00:00:00Z,6,23,sunbricks,1,yes,once,3,cow_cart;bicycle;radio;cow_plough;solar_panel;...,3,none,uuid:c90eade0-1148-4a12-8c0e-6387a36f45b1
37,38,God,2016-11-17T00:00:00Z,10,19,muddaub,1,yes,never,3,bicycle;radio;cow_plough;solar_panel;table;mob...,3,Nov,uuid:81309594-ff58-4dc1-83a7-72af5952ee08
39,40,God,2016-11-17T00:00:00Z,9,23,burntbricks,1,yes,never,1,bicycle;radio;cow_plough;solar_panel;table;mob...,3,Sept;Oct;Nov,uuid:c0b34854-eede-4e81-b183-ef58a45bfc34
41,42,God,2016-11-17T00:00:00Z,8,8,sunbricks,1,no,never,3,mobile_phone,3,Jan;Nov;Dec,uuid:e3a1dd8a-1bda-428c-a014-2b527f11ae64
42,43,Chirodzo,2016-11-17T00:00:00Z,7,29,muddaub,1,no,never,2,cow_plough;mobile_phone,2,Jan;Feb;Oct;Nov;Dec,uuid:b4dff49f-ef27-40e5-a9d1-acf287b47358
44,45,Chirodzo,2016-11-17T00:00:00Z,9,7,muddaub,1,no,never,4,motorcyle;bicycle;television;radio;cow_plough;...,3,none,uuid:e3554d22-35b1-4fb9-b386-dd5866ad5792
45,46,Chirodzo,2016-11-17T00:00:00Z,10,42,burntbricks,2,no,once,2,motorcyle;computer;television;sterio;solar_pan...,2,Sept;Oct;Nov,uuid:35f297e0-aa5d-4149-9b7b-4965004cfc37
46,47,Chirodzo,2016-11-17T00:00:00Z,2,2,muddaub,1,yes,once,1,solar_torch;mobile_phone,3,none,uuid:2d0b1936-4f82-4ec3-a3b5-7c3c8cd6cc2b
49,50,Chirodzo,2016-11-16T00:00:00Z,6,7,muddaub,1,yes,never,1,solar_torch,2,June;July;Aug;Sept;Oct;Nov;Dec,uuid:4267c33c-53a7-46d9-8bd6-b96f58a4f92c
51,52,Chirodzo,2016-11-16T00:00:00Z,11,15,burntbricks,3,no,never,3,motorcyle;television;radio;cow_plough;solar_pa...,3,Aug;Sept;Oct;Nov,uuid:6db55cb4-a853-4000-9555-757b7fae2bcf
52,21,Chirodzo,2016-11-16T00:00:00Z,8,16,burntbricks,3,yes,frequently,2,bicycle;radio;mobile_phone,2,Nov,uuid:cc7f75c5-d13e-43f3-97e5-4f4c03cb4b12
55,56,Chirodzo,2016-11-16T00:00:00Z,12,23,burntbricks,2,yes,never,2,motorcyle;bicycle;mobile_phone,3,none,uuid:973c4ac6-f887-48e7-aeaf-4476f2cfab76
56,57,Chirodzo,2016-11-16T00:00:00Z,4,27,burntbricks,1,no,never,1,radio,2,none,uuid:a7184e55-0615-492d-9835-8f44f3b03a71
57,58,Chirodzo,2016-11-16T00:00:00Z,11,45,burntbricks,3,no,never,3,motorcyle;bicycle;television;radio;cow_plough;...,2,none,uuid:a7a3451f-cd0d-4027-82d9-8dcd1234fcca
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,101,God,2017-04-27T00:00:00Z,3,4,muddaub,1,no,never,1,bicycle;solar_torch,3,Sept;Oct;Nov,uuid:3c174acd-e431-4523-9ad6-eb14cddca805
96,103,Ruaca,2017-04-27T00:00:00Z,6,96,sunbricks,1,no,never,5,cow_cart;cow_plough;solar_panel;sofa_set;mobil...,3,Jan;Feb;Dec,uuid:e9d79844-ef14-493b-bbd6-d13691cc660e
97,102,Ruaca,2017-04-28T00:00:00Z,12,15,burntbricks,2,yes,frequently,2,cow_plough;table;sofa_set;mobile_phone,3,Jan;Feb,uuid:76206b0b-af74-4344-b24f-81e839f0d7b0
98,78,Ruaca,2017-04-28T00:00:00Z,6,48,burntbricks,1,no,more_once,2,cow_plough,2,Aug;Sept;Oct,uuid:da3fa7cc-5ce9-44fd-9a78-b8982b607515
99,80,Ruaca,2017-04-28T00:00:00Z,5,12,muddaub,1,no,more_once,1,cow_cart;bicycle;radio;cow_plough;solar_panel;...,3,none,uuid:a85df6df-0336-46fa-a9f4-522bf6f8b438
100,104,Ruaca,2017-04-28T00:00:00Z,14,52,sunbricks,1,yes,never,4,cow_cart;bicycle;cow_plough,3,Jan;Feb;Dec,uuid:bb2bb365-7d7d-4fe9-9353-b21269676119
101,105,Ruaca,2017-04-28T00:00:00Z,6,40,sunbricks,1,yes,frequently,2,motorcyle;radio;cow_plough;solar_panel;mobile_...,3,Jan;Feb;Dec,uuid:af0904ee-4fdb-4090-973f-599c81ddf022
102,106,God,2017-04-30T00:00:00Z,15,22,sunbricks,5,no,never,2,cow_cart;motorcyle;bicycle;radio;sterio;cow_pl...,3,Oct;Nov;Dec,uuid:468797c1-4a65-4f35-9c83-e28ce46972a2
104,110,Ruaca,2017-05-03T00:00:00Z,6,22,sunbricks,3,no,never,3,bicycle;radio;cow_plough;table;mobile_phone,2,none,uuid:e7c51ac4-24e4-475e-88e7-f85e896945e3
105,113,Ruaca,2017-05-03T00:00:00Z,11,26,burntbricks,3,no,never,4,cow_cart;motorcyle;bicycle;radio;cow_plough;so...,3,none,uuid:01210861-aba1-4268-98d0-0260e05f5155
107,125,Ruaca,2017-05-04T00:00:00Z,5,14,burntbricks,1,no,more_once,2,bicycle;radio;cow_plough;solar_panel;solar_tor...,3,Jan;Sept;Oct;Nov;Dec,uuid:02b05c68-302e-4e7a-b229-81cb1377fd29
108,119,Ruaca,2017-05-04T00:00:00Z,3,14,muddaub,1,no,never,4,bicycle;cow_plough;solar_panel;mobile_phone,3,none,uuid:fa201fce-4e94-44b8-b435-c558c2e1ed55
110,108,God,2017-05-11T00:00:00Z,15,22,burntbricks,2,no,never,4,cow_cart;bicycle;radio;cow_plough;solar_panel;...,3,Aug;Sept;Oct;Nov,uuid:e4f4d6ba-e698-45a5-947f-ba6da88cc22b
113,144,Ruaca,2017-05-18T00:00:00Z,7,5,burntbricks,4,no,frequently,4,cow_cart;television;radio;cow_plough;solar_pan...,2,none,uuid:0670cef6-d233-4852-89d8-36955261b0a3
114,143,Ruaca,2017-05-18T00:00:00Z,10,24,burntbricks,2,no,frequently,3,cow_cart;motorcyle;television;radio;cow_plough...,3,Jan;Dec,uuid:9a096a12-b335-468c-b3cc-1191180d62de
115,150,Ruaca,2017-05-18T00:00:00Z,7,8,muddaub,1,no,never,1,mobile_phone,3,Sept;Oct;Nov,uuid:92613d0d-e7b1-4d62-8ea4-451d7cd0a982
116,159,God,2017-05-18T00:00:00Z,4,24,sunbricks,1,no,never,1,radio;solar_panel;solar_torch,3,Sept;Oct;Nov,uuid:37577f91-d665-443e-8d70-b914954cef4b
117,160,God,2017-06-03T00:00:00Z,7,13,burntbricks,2,yes,frequently,2,cow_cart;cow_plough;solar_torch;mobile_phone,2,Nov,uuid:f22831ec-6bc3-4b73-9197-4b01e01abb66
118,165,Ruaca,2017-06-03T00:00:00Z,9,14,burntbricks,1,no,never,3,cow_cart;motorcyle;bicycle;television;radio;co...,3,none,uuid:62f3f7af-f0f3-4f88-b9e0-acf8baa49ae4
119,166,Ruaca,2017-06-03T00:00:00Z,11,16,muddaub,1,no,never,1,bicycle;solar_torch;mobile_phone,2,Feb;Mar,uuid:40aac732-94df-496c-97ba-5b67f59bcc7a
120,167,Ruaca,2017-06-03T00:00:00Z,8,24,muddaub,1,no,never,3,motorcyle;radio;cow_plough;solar_panel;solar_t...,2,Jan;Nov;Dec,uuid:a9d1a013-043b-475d-a71b-77ed80abe970
121,174,Ruaca,2017-06-03T00:00:00Z,12,25,burntbricks,2,no,never,3,car;lorry;motorcyle;radio;sterio;cow_plough;so...,3,Jan;Feb;Dec,uuid:43ec6132-478c-4f87-878d-fb3c0c4d0c74
122,175,Ruaca,2017-06-03T00:00:00Z,7,36,burntbricks,1,no,never,4,motorcyle;bicycle;radio;sterio;cow_plough;sola...,2,Jan;Oct;Nov;Dec,uuid:64fc743e-8176-40f6-8ae4-36ae97fac1d9
123,189,Ruaca,2017-06-03T00:00:00Z,15,16,sunbricks,1,no,never,3,motorcyle;radio;sterio;cow_plough;solar_panel;...,3,Nov,uuid:c17e374c-280b-4e78-bf21-74a7c1c73492
124,191,Ruaca,2017-06-03T00:00:00Z,10,5,burntbricks,4,no,never,1,radio;cow_plough;solar_panel;solar_torch;mobil...,2,Oct;Nov;Dec,uuid:dad53aff-b520-4015-a9e3-f5fdf9168fe1
125,192,Chirodzo,2017-06-03T00:00:00Z,9,20,burntbricks,1,no,once,1,bicycle;television;radio;sterio;solar_panel;so...,3,Jan;Nov;Dec,uuid:f94409a6-e461-4e4c-a6fb-0072d3d58b00
126,126,Ruaca,2017-05-18T00:00:00Z,3,7,burntbricks,1,no,more_once,3,motorcyle;radio;solar_panel,3,Oct;Nov;Dec,uuid:69caea81-a4e5-4e8d-83cd-9c18d8e8d965
127,193,Ruaca,2017-06-04T00:00:00Z,7,10,cement,3,no,more_once,3,car;lorry;television;radio;sterio;cow_plough;s...,3,none,uuid:5ccc2e5a-ea90-48b5-8542-69400d5334df
128,194,Ruaca,2017-06-04T00:00:00Z,4,5,muddaub,1,no,more_once,1,radio;solar_panel;solar_torch;mobile_phone,3,Sept;Oct;Nov,uuid:95c11a30-d44f-40c4-8ea8-ec34fca6bbbf
129,199,Chirodzo,2017-06-04T00:00:00Z,7,17,burntbricks,2,yes,more_once,2,cow_cart;lorry;motorcyle;computer;television;r...,3,Nov;Dec,uuid:ffc83162-ff24-4a87-8709-eff17abc0b3b

In [21]:
# create a grouped_by object in which our data are grouped by 'village'
grouped_by = safi.groupby("village")

In [22]:
# then operate count on the grouped object --> returns the count for column per village
grouped_by.count()

,key_ID,interview_date,no_membrs,years_liv,respondent_wall_type,rooms,memb_assoc,affect_conflicts,liv_count,items_owned,no_meals,months_lack_food,instanceID
village,,,,,,,,,,,,,
Chirodzo,39,39,39,39,39,39,27,27,39,36,39,39,39
God,43,43,43,43,43,43,25,25,43,39,43,43,43
Ruaca,49,49,49,49,49,49,40,40,49,46,49,49,49

In [23]:
# create an object no_members that holds the mean value of 'no_membrs' calculated per 'village' ad 'affect_conflicts'
no_membrs = safi.groupby(['village','affect_conflicts']).mean()['no_membrs']

In [18]:
no_membrs

village   affect_conflicts
Chirodzo  frequently           9.000000
          more_once            6.875000
          never                8.916667
          once                 7.000000
God       frequently           7.000000
          more_once            8.000000
          never                7.428571
          once                 6.000000
Ruaca     frequently           7.833333
          more_once            7.307692
          never                8.150000
          once                10.000000
Name: no_membrs, dtype: float64

# %load code/groupby
1. Read in the SAFI_clean.csv dataset.
2. Get a list of the different `rooms` values.
3. Groupby `rooms` and describe the results.
4. Remove all rows with NaN values.
5. repeat steps 2 & 3 and compare the results.

### Solution to exercise

In [24]:
# 1.
safi = pd.read_csv('data/SAFI_clean.csv')

In [25]:
# 2. 
safi['rooms'].unique()

array([1, 3, 5, 2, 4, 8])

In [27]:
# 3.
safi.groupby('rooms').describe()

      key_ID                                                            \
       count        mean        std    min    25%    50%    75%    max
rooms
1       73.0   78.958904  61.534416    1.0   33.0   61.0  125.0  198.0
2       33.0  100.515152  66.276938   15.0   46.0   76.0  174.0  201.0
3       17.0   70.352941  55.865845    8.0   25.0   59.0  110.0  193.0
4        5.0  135.400000  71.716804   23.0  117.0  144.0  191.0  202.0
5        2.0   58.000000  67.882251   10.0   34.0   58.0   82.0  106.0
8        1.0  127.000000        NaN  127.0  127.0  127.0  127.0  127.0

      liv_count            ...  no_membrs       years_liv             \
          count      mean  ...        75%   max     count       mean
rooms                      ...
1          73.0  2.068493  ...       7.00  15.0      73.0  21.095890
2          33.0  2.848485  ...      10.00  19.0      33.0  26.181818
3          17.0  2.823529  ...      11.00  12.0      17.0  28.411765
4           5.0  2.400000  ...      10.00  12.0       5.0  14.000000
5           2.0  2.000000  ...      14.25  15.0       2.0  22.500000
8           1.0  1.000000  ...       4.00   4.0       1.0  18.000000


             std   min    25%   50%    75%   max
rooms
1      17.158707   1.0   8.00  16.0  27.00  96.0
2      16.602813   4.0  16.00  23.0  30.00  79.0
3      18.100617   6.0  18.00  21.0  37.00  70.0
4       9.974969   5.0   5.00  12.0  20.00  28.0
5       0.707107  22.0  22.25  22.5  22.75  23.0
8            NaN  18.0  18.00  18.0  18.00  18.0

[6 rows x 40 columns]

In [28]:
# 4. and 5.
safi.dropna().groupby('rooms').describe()

      key_ID                                                             \
       count        mean        std    min     25%    50%    75%    max
rooms
1       44.0   98.295455  60.959605    1.0   44.50   84.0  160.5  195.0
2       25.0  104.840000  63.948339   15.0   56.00   89.0  174.0  199.0
3       14.0   71.928571  58.515566    8.0   27.25   61.5   99.5  193.0
4        3.0  179.000000  30.805844  144.0  167.50  191.0  196.5  202.0
5        2.0   58.000000  67.882251   10.0   34.00   58.0   82.0  106.0

      liv_count            ...  no_membrs       years_liv             \
          count      mean  ...        75%   max     count       mean
rooms                      ...
1          44.0  2.318182  ...       8.25  15.0      44.0  23.000000
2          25.0  3.080000  ...      11.00  19.0      25.0  27.680000
3          14.0  2.785714  ...      11.00  12.0      14.0  27.000000
4           3.0  2.666667  ...      11.00  12.0       3.0   7.333333
5           2.0  2.000000  ...      14.25  15.0       2.0  22.500000


             std   min    25%   50%    75%   max
rooms
1      17.885944   2.0  11.25  17.5  30.25  96.0
2      18.350114   4.0  15.00  24.0  31.00  79.0
3      17.832555   6.0  16.50  20.5  34.25  70.0
4       4.041452   5.0   5.00   5.0   8.50  12.0
5       0.707107  22.0  22.25  22.5  22.75  23.0

[5 rows x 40 columns]

### explanation:
- by dropping all missing data we remove the rows where rooms is 8 and the summary statistics for the variables is different to our original data (the one including missing data)